# Generated by Django 4.0.6 on 2022-11-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='entity',
            new_name='quantity',
        ),
    ]
